name = "Fabric Pack 1"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bde60ea3e7828eba04a43da6070b99df7e85f65ea890c757b5bf0798540d419"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
