name = "Fabric Pack 1"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98271906c598ea6e9a87c6056511af559eab751622ae40411de9ecd26219e563"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
