name = "Fabric Pack 1"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6404ad2486544536e845d27ba2d693df4d1d608db79c4aef636c7d897aa85b3b"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
