name = "Fabric Pack 1"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f76db05f651fecff8bc0715a7342b5a8a44384a5d25e71166b521448d3ef801"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
