name = "Fabric Pack 1"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd48f883e72b0f322190354b70984f29c955ef00d4860ae853db1d42c5d9abbf"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
