name = "Fabric Pack 1"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a28e9e46de6e00b14192339fae52c84fff5a3632c4bfe785f961b7df6524efc0"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
