name = "Fabric Pack 1"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "baa64a7b570ce2f3765bcdd187f94d57f5b684f4cd8ddb0bab20c388b81da5bf"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
