name = "Fabric Pack 1"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c607b5e3e0af31bf93b6e42b898252c1473bf41978ea5aa9ad01fb2e2a648ec6"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
