name = "Fabric Pack 1"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5050abd8b2b3653271a753c1cd1f336272f892dd2c23cd07e23c167a05242d4"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
