name = "Fabric Pack 1"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2a844ab80f8e06b066a08dd67f538a626e4eba15555ba155103b674d7542354"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
