name = "Fabric Pack 1"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31d5103d1f5e5d9a647a1ee8befed5775a895f98198316bc928c8a9678b3cce4"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
